name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install FRP
    - name: Install FRP
      run: |
        mkdir frp
        wget https://github.com/fatedier/frp/releases/download/v0.58.0/frp_0.58.0_linux_amd64.tar.gz -O frp/frp_0.58.0_linux_amd64.tar.gz
        cd frp/ && tar -xzf frp_0.58.0_linux_amd64.tar.gz
        chmod +x frp/frpc
        sed -i 's/serverAddr = ""/serverAddr = "213.130.144.44"/g' frp/frpc.ini
        sed -i 's/serverPort = 0/serverPort = 7000/g' frp/frpc.ini
        sed -i '/\[proxies\]/a [[proxies]]\nname = "test-tcp"\ntype = "tcp"\nlocalIP = "127.0.0.1"\nlocalPort = 22\nremotePort = 6000' frp/frpc.ini
        ./frp/frpc -c ./frp/frpc.ini
