name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install FRP
    - name: Install FRP
      run: |
        mkdir /t/
        wget https://github.com/fatedier/frp/releases/download/v0.58.0/frp_0.58.0_linux_amd64.tar.gz /t/
        cd /t/ && tar -xzf frp_0.58.0_linux_amd64.tar.gz
        cd /t/ && chmod +x frp_0.58.0_linux_amd64.tar.gz
        cd /t/fr* && sed -i 's/serverAddr = ""/serverAddr = "213.130.144.44"/g' frpc.toml
        cd /t/fr* sed -i 's/serverPort = 0/serverPort = 7000/g' frpc.toml
        cd /t/fr* sed -i '/\[proxies\]/a [[proxies]]\nname = "test-tcp"\ntype = "tcp"\nlocalIP = "127.0.0.1"\nlocalPort = 22\nremotePort = 6000' frpc.toml
        /t/frp_0.58.0_linux_amd64/frpc -c frpc.toml
    # Run frpc
    - name: Run frpc
      run: |
        ./frpc -c frpc.toml
